### ISSUE TITLE
machine-controller-manager启动失败 bind: address already in use

### ISSUE THREAD

**Issue by xuanyunhui** [AliyunContainerService/cluster-api-provider-alibabacloud#1]
Client Version: v4.2.0-alpha.0-87-gd5465d7
Server Version: 4.1.18
Kubernetes Version: v1.13.4+c2a5caf

oc -n openshift-machine-api create -f https://raw.githubusercontent.com/AliyunContainerService/cluster-api-provider-alibabacloud/master/config/controllers/deployment.yaml

启动后machine-controller-manager容器报错信息

I1021 07:25:15.690267       1 request.go:530] Throttling request took 90.747233ms, request: GET:https://172.30.0.1:443/apis/autoscaling.openshift.io/v1beta1?timeout=32s
I1021 07:25:15.740246       1 request.go:530] Throttling request took 140.722406ms, request: GET:https://172.30.0.1:443/apis/cloudcredential.openshift.io/v1?timeout=32s
I1021 07:25:15.790379       1 request.go:530] Throttling request took 190.842175ms, request: GET:https://172.30.0.1:443/apis/imageregistry.operator.openshift.io/v1?timeout=32s
I1021 07:25:15.840395       1 request.go:530] Throttling request took 240.852989ms, request: GET:https://172.30.0.1:443/apis/k8s.cni.cncf.io/v1?timeout=32s
I1021 07:25:15.890240       1 request.go:530] Throttling request took 290.693776ms, request: GET:https://172.30.0.1:443/apis/machineconfiguration.openshift.io/v1?timeout=32s
I1021 07:25:15.940348       1 request.go:530] Throttling request took 340.795461ms, request: GET:https://172.30.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s
I1021 07:25:15.990358       1 request.go:530] Throttling request took 390.790026ms, request: GET:https://172.30.0.1:443/apis/network.openshift.io/v1?timeout=32s
I1021 07:25:16.040242       1 request.go:530] Throttling request took 440.673957ms, request: GET:https://172.30.0.1:443/apis/operators.coreos.com/v1?timeout=32s
I1021 07:25:16.090265       1 request.go:530] Throttling request took 490.690327ms, request: GET:https://172.30.0.1:443/apis/batch/v1beta1?timeout=32s
I1021 07:25:16.140360       1 request.go:530] Throttling request took 540.781977ms, request: GET:https://172.30.0.1:443/apis/operators.coreos.com/v1alpha2?timeout=32s
I1021 07:25:16.190243       1 request.go:530] Throttling request took 590.658192ms, request: GET:https://172.30.0.1:443/apis/certificates.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.240240       1 request.go:530] Throttling request took 640.653745ms, request: GET:https://172.30.0.1:443/apis/operators.coreos.com/v1alpha1?timeout=32s
I1021 07:25:16.290236       1 request.go:530] Throttling request took 690.645366ms, request: GET:https://172.30.0.1:443/apis/networking.k8s.io/v1?timeout=32s
I1021 07:25:16.340283       1 request.go:530] Throttling request took 740.68726ms, request: GET:https://172.30.0.1:443/apis/samples.operator.openshift.io/v1?timeout=32s
I1021 07:25:16.390344       1 request.go:530] Throttling request took 790.746019ms, request: GET:https://172.30.0.1:443/apis/policy/v1beta1?timeout=32s
I1021 07:25:16.440235       1 request.go:530] Throttling request took 840.637173ms, request: GET:https://172.30.0.1:443/apis/tuned.openshift.io/v1?timeout=32s
I1021 07:25:16.490235       1 request.go:530] Throttling request took 890.628751ms, request: GET:https://172.30.0.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
I1021 07:25:16.540350       1 request.go:530] Throttling request took 940.727059ms, request: GET:https://172.30.0.1:443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.590273       1 request.go:530] Throttling request took 990.63693ms, request: GET:https://172.30.0.1:443/apis/storage.k8s.io/v1?timeout=32s
I1021 07:25:16.640256       1 request.go:530] Throttling request took 1.040614406s, request: GET:https://172.30.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.690275       1 request.go:530] Throttling request took 1.090628608s, request: GET:https://172.30.0.1:443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.740376       1 request.go:530] Throttling request took 1.140728365s, request: GET:https://172.30.0.1:443/apis/apiextensions.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.790247       1 request.go:530] Throttling request took 1.190587183s, request: GET:https://172.30.0.1:443/apis/scheduling.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.840368       1 request.go:530] Throttling request took 1.240699196s, request: GET:https://172.30.0.1:443/apis/csi.storage.k8s.io/v1alpha1?timeout=32s
I1021 07:25:16.890287       1 request.go:530] Throttling request took 1.290610507s, request: GET:https://172.30.0.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s
I1021 07:25:16.940291       1 request.go:530] Throttling request took 1.34061369s, request: GET:https://172.30.0.1:443/apis/healthchecking.openshift.io/v1alpha1?timeout=32s
I1021 07:25:16.990237       1 request.go:530] Throttling request took 1.390556205s, request: GET:https://172.30.0.1:443/apis/machine.openshift.io/v1beta1?timeout=32s
I1021 07:25:17.040474       1 request.go:530] Throttling request took 1.440790016s, request: GET:https://172.30.0.1:443/apis/apps.openshift.io/v1?timeout=32s
I1021 07:25:17.090245       1 request.go:530] Throttling request took 1.490554269s, request: GET:https://172.30.0.1:443/apis/authorization.openshift.io/v1?timeout=32s
I1021 07:25:17.140351       1 request.go:530] Throttling request took 1.540638827s, request: GET:https://172.30.0.1:443/apis/build.openshift.io/v1?timeout=32s
F1021 07:25:17.148059       1 main.go:76] Error creating manager: error listening on :8080: listen tcp :8080: bind: address already in use

**Comment by menglingwei** [comment]
@xuanyunhui  我来排查一下。

**Comment by menglingwei** [comment]
@xuanyunhui  你在试下

**Comment by xuanyunhui** [comment]
Test with OpenShift 4.5.0-rc.5 is working
